# https://www.docker.elastic.co/#
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2 

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

RUN elasticsearch-plugin install lmenezes/elasticsearch-kopf/2.0
