# https://www.docker.elastic.co/#
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2 

# Add your elasticsearch plugins setup here
# Example: RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu
